apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: k3dclusters.k3d.io
spec:
  group: k3d.io
  scope: Namespaced
  names:
    plural: k3dclusters
    singular: k3dcluster
    kind: K3dCluster
    shortNames:
    - k3d
  versions:
  - name: v1alpha3
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties: {}
